# Generated by Django 5.1.4 on 2026-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The uploaded text snippet.')),
                ('ai_tag', models.CharField(choices=[('Technical', 'Technical'), ('Urgent', 'Urgent'), ('General', 'General')], default='General', help_text='Tag automatically assigned by the AI engine.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Knowledge Item',
                'verbose_name_plural': 'Knowledge Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
